---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

#- name: Update all packages to the latest version
#  apt:
#   upgrade: dist
#    update_cache: yes
#    cache_valid_time: 3600

- name: Install Generic Tools
  become: yes
  apt: 
    name: ['htop', 'vim', 'git', 'iftop', 'acl', 'apache2-utils', 'nmap', 'whois', 'docker.io', 'sqlite3', 'vnstat', 'docker-compose']
    update_cache: yes 
    cache_valid_time: 3600
    state: latest
...
