---
- name: make torrent paths
  become: yes
  file:
    path: "{{ item.0.root_dir }}/{{ item.1 }}"
    state: "{{ item.0.state }}"
    owner: "{{ item.0.owner }}"
    group: "{{ item.0.group }}"
    mode : "{{ item.0.mode }}"
  with_subelements: 
    - "{{ paths_to_create }}"
    - subdirs

- name: make container symlinks
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    state: link
  with_items: 
    - "{{ links_to_create }}"

- name: copy docker scripts
  copy:
    src: "{{ item }}"
    dest: /root/
    mode:  0640
  with_fileglob:
    - files/docker-compose.yml

- name : copy sickchill conf
  copy:
    src: files/sickchill/config.ini
    dest: /home/torrent/sickchill/config/config.ini
    mode: 0640
    owner: torrent
    group: torrent
    force: no

- name : copy qBittorent conf
  copy:
    src: files/qbittorrent/qBittorrent.conf
    dest: /home/torrent/qbittorrent/config/qBittorrent/
    mode: 0640
    owner: torrent
    group: torrent
    force: no

- name : copy headphones conf
  copy:
    src: files/headphones/config.ini
    dest: /home/torrent/headphones/data/config.ini
    mode: 0640
    owner: torrent
    group: torrent
    force: no

- name : copy jackett conf
  copy:
    src: files/jackett/ServerConfig.json
    dest: /home/torrent/jackett/data/Jackett/ServerConfig.json
    mode: 0640
    owner: torrent
    group: torrent
    force: no