global:
 scrape_interval: 5s
scrape_configs:
 - job_name: 'prometheus'
   metrics_path: "/prometheus/metrics"
   static_configs:
     - targets: ['prometheus:9090'] ## IP Address of the localhost
 - job_name: 'node-exporter'
   static_configs:
     - targets: ['node-exporter:9100']
 - job_name: 'cAdvisor'
   static_configs:
     - targets: ['cadvisor:8080']
