paths_to_create:
  - root_dir: /home/torrent
    subdirs:
      - sickchill
      - sickchill/config
      - qbittorrent/config/qBittorrent
      - nginx
      - headphones
      - jackett/data
      - monitoring
    owner: torrent
    group: torrent
    mode: "0750"
    state: directory

  - root_dir: /home/torrent
    subdirs:
      - downloads
      - downloads/complete
      - downloads/incomplete
      - downloads/watch
      - sickchill/tv
      - headphones/data
      - headphones/music
      - jackett/data/Jackett
      - monitoring/grafana-storage
    owner: torrent
    group: torrent
    mode: "2770"
    state: directory

  - root_dir: /home/torrent
    subdirs:
      - nginx
      - nginx/nginx/site-confs
      - nginx/www/.well-known
    owner: torrent
    group: torrent
    mode: "0770"
    state: directory

  - root_dir: /var
    subdirs:
      - backup_conf
    owner: torrent
    group: torrent
    mode: "0750"
    state: directory

links_to_create:
  - dest: /home/torrent/sickchill/downloads
    src: /home/torrent/downloads/complete
    owner: torrent
    group: torrent

  - dest: /tv
    src: /home/torrent/sickchill/tv
    owner: torrent
    group: torrent
