version: '3'
services:
  sickchill:
    image: linuxserver/sickchill
    container_name: sickchill
    volumes:
      - /home/torrent/sickchill/config:/config
      - /home/torrent/downloads:/downloads
      - /home/torrent/sickchill/tv:/tv
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Paris
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - netbridge
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    networks:
      - netbridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/torrent/nginx:/config
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Paris
    restart: unless-stopped
    depends_on:
      - sickchill
      - headphones
      - jackett
      - grafana
      - prometheus
      - qbittorrent
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    volumes:
      - /home/torrent/headphones/data:/config
      - /home/torrent/downloads:/downloads
      - /home/torrent/headphones/music:/music
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - netbridge
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - /home/torrent/jackett/data:/config
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - netbridge
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /home/torrent/qbittorrent/config:/config
      - /home/torrent/downloads:/downloads
      - /home/torrent/sickchill/tv:/tv
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - netbridge
  prometheus:
    user: "0"
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/torrent/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=http://prometheus:9090/prometheus/"
      - '--storage.tsdb.retention.time=200h'
    restart: unless-stopped
    networks:
      - netbridge
    depends_on:
      - node-exporter
      - cadvisor
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - netbridge
  cadvisor:
    image: gcr.io/google-containers/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    restart: unless-stopped
    networks:
      - netbridge
  grafana:
    user: "1001"
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /home/torrent/monitoring/grafana-storage:/var/lib/grafana
      - /home/torrent/monitoring/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped
    networks:
      - netbridge
    depends_on:
      - prometheus
networks:
  netbridge:
    driver: bridge
volumes:
  prometheus-storage: {}
